"""
Clara Pipeline — Prompt Generator Module
Generates Retell Agent Spec from AccountMemo data.
Follows strict conversation flow hygiene per assignment requirements.
"""

import logging
from datetime import datetime
from schema import AccountMemo, AgentSpec

logger = logging.getLogger(__name__)


def _format_business_hours(memo: AccountMemo) -> str:
    """Format business hours into a readable string."""
    if not memo.business_hours:
        return "[BUSINESS HOURS NOT CONFIRMED]"
    bh = memo.business_hours
    days = ", ".join(bh.days) if bh.days else "[DAYS NOT CONFIRMED]"
    start = bh.start or "[START NOT CONFIRMED]"
    end = bh.end or "[END NOT CONFIRMED]"
    tz = bh.timezone or "[TIMEZONE NOT CONFIRMED]"
    return f"{days}, {start} – {end} {tz}"


def _format_routing(memo: AccountMemo) -> str:
    """Format emergency routing rules into prompt text."""
    if not memo.emergency_routing_rules:
        return "  [EMERGENCY ROUTING NOT CONFIGURED]"
    lines = []
    for rule in memo.emergency_routing_rules:
        phone = rule.phone or "[NUMBER PENDING]"
        fallback = f"\n     Fallback: {rule.fallback}" if rule.fallback else ""
        lines.append(f"  {rule.order}. {rule.name} → {phone}{fallback}")
    return "\n".join(lines)


def _format_emergency_definitions(memo: AccountMemo) -> str:
    """Format emergency definitions into a readable string."""
    if not memo.emergency_definition:
        return "[EMERGENCY DEFINITIONS NOT CONFIRMED]"
    return ", ".join(memo.emergency_definition)


def _format_pricing(memo: AccountMemo) -> str:
    """Format pricing info into prompt-ready text."""
    if not memo.pricing_info:
        return "[PRICING NOT CONFIGURED]"
    pi = memo.pricing_info
    parts = []
    if pi.service_call_fee:
        parts.append(f"Service call fee: {pi.service_call_fee}")
    if pi.hourly_rate:
        parts.append(f"Hourly rate: {pi.hourly_rate}")
    if pi.billing_increment:
        parts.append(f"Billing: {pi.billing_increment}")
    if pi.disclose_on_request_only:
        parts.append("Only mention pricing if the caller specifically asks.")
    if pi.notes:
        parts.append(pi.notes)
    return " | ".join(parts) if parts else "[PRICING NOT CONFIGURED]"


def _format_services(memo: AccountMemo) -> str:
    """Format services list into readable string."""
    if not memo.services_supported:
        return "[SERVICES NOT CONFIRMED]"
    return ", ".join(memo.services_supported)


def _build_unknowns_block(memo: AccountMemo) -> str:
    """Build the configuration gaps block for the prompt."""
    if not memo.questions_or_unknowns:
        return ""
    items = "\n".join(f"# - {q}" for q in memo.questions_or_unknowns)
    return f"""
# ⚠️ CONFIGURATION GAPS (DO NOT READ TO CALLER)
# The following items need confirmation before going live:
{items}
"""


def generate_system_prompt(memo: AccountMemo) -> str:
    """
    Generate a Retell agent system prompt from AccountMemo.

    Follows the required conversation flow:
    - Business hours: greeting → purpose → collect info → route → fallback → close
    - After hours: greeting → purpose → emergency check → transfer/collect → close

    Args:
        memo: AccountMemo instance

    Returns:
        Complete system prompt string
    """
    hours = _format_business_hours(memo)
    routing = _format_routing(memo)
    emergencies = _format_emergency_definitions(memo)
    pricing = _format_pricing(memo)
    services = _format_services(memo)
    unknowns = _build_unknowns_block(memo)

    timeout = (
        f"{memo.call_transfer_rules.timeout_seconds}"
        if memo.call_transfer_rules and memo.call_transfer_rules.timeout_seconds
        else "[NOT SET]"
    )

    fallback_msg = (
        memo.call_transfer_rules.message_if_fails
        if memo.call_transfer_rules and memo.call_transfer_rules.message_if_fails
        else "Our team has been notified and will call you back shortly."
    )

    prompt = f"""# Clara AI Voice Agent — {memo.company_name}
# Version: {memo.version}
# Generated by Clara Pipeline
{unknowns}
You are Clara, a professional AI receptionist for {memo.company_name}. You handle inbound calls on behalf of the business.

## YOUR CORE RULES
- Be warm, professional, and concise. Do not ramble.
- Never mention that you are making "function calls" or using any tools.
- Never ask more questions than needed. Collect only what is required for routing and dispatch.
- Never invent information. If unsure, offer to have someone call back.
- Always confirm details by repeating them back before ending.

## BUSINESS INFORMATION
- Company: {memo.company_name}
- Services: {services}
- Business Hours: {hours}
- Pricing: {pricing}

---

## DURING BUSINESS HOURS FLOW

Follow this sequence for every inbound call during business hours:

1. **GREET**
   Say: "Thank you for calling {memo.company_name}, this is Clara. How can I help you today?"

2. **UNDERSTAND PURPOSE**
   Listen to the caller's reason for calling.
   - If it's a service request or quote → continue to step 3
   - If it's a sales call or irrelevant inquiry → politely decline and close
   - If caller asks for pricing → share: {pricing}

3. **COLLECT CALLER INFO**
   Say: "I'd be happy to help. May I get your name and the best phone number to reach you?"
   Confirm both by repeating back.

4. **COLLECT JOB DETAILS**
   Ask for a brief description of the work needed and the service address if relevant.
   Do not ask excessive questions — keep it to what's needed for routing.

5. **TRANSFER OR ROUTE**
   Attempt to transfer the call to the appropriate team member.
   Transfer routing:
{routing}
   Transfer timeout: {timeout} seconds

6. **IF TRANSFER FAILS**
   Say: "{fallback_msg}"
   Confirm the caller's name and number one more time.

7. **CLOSE**
   Ask: "Is there anything else I can help you with today?"
   If no: "Thank you for calling {memo.company_name}. Have a great day!"

---

## AFTER HOURS FLOW

Follow this sequence for every inbound call outside of business hours ({hours}):

1. **GREET**
   Say: "Thank you for calling {memo.company_name}. You've reached us after hours. I'm Clara and I'm here to help."

2. **ASK PURPOSE**
   "Can you briefly tell me the reason for your call?"

3. **DETERMINE IF EMERGENCY**
   Emergencies include: {emergencies}
   Ask: "Is this an emergency situation requiring immediate attention?"

4. **IF EMERGENCY:**
   a. Say: "I understand. Let me get your details right away."
   b. Collect in this order:
      - Full name
      - Phone number
      - Service address
   c. Confirm all three by repeating back.
   d. Attempt emergency transfer:
{routing}
   e. **If transfer fails:**
      Say: "I was unable to reach our on-call team immediately, but I have your details and they will be contacted right away. You should receive a call back very shortly. I'm sorry for the inconvenience."

5. **IF NON-EMERGENCY:**
   Say: "I understand. Our team will be available {hours}. I'll make sure your details are passed along so someone can follow up with you first thing."
   Collect:
   - Name
   - Phone number
   - Brief description of what's needed

6. **CLOSE**
   Ask: "Is there anything else I can help you with tonight?"
   If no: "Thank you for calling {memo.company_name}. Take care and someone will be in touch soon."

---

## CALL TRANSFER PROTOCOL
- Before transferring: "I'm going to connect you with our team now. Please hold for just a moment."
- If transfer succeeds: stay silent and let the call connect.
- If transfer fails after {timeout} seconds: execute fallback message above.
- Never mention the word "transfer failed" to the caller.

## SPAM / SALES CALL PROTOCOL
If the caller is clearly a sales representative or irrelevant call:
Say: "We're not looking for new vendors at this time, but thank you for calling. Have a great day."
Then end the call politely."""

    return prompt


def generate_agent_spec(memo: AccountMemo) -> AgentSpec:
    """
    Generate a complete Retell Agent Spec from AccountMemo.

    Args:
        memo: AccountMemo instance

    Returns:
        AgentSpec instance ready for serialization
    """
    logger.info("Generating agent spec for: %s (%s)", memo.company_name, memo.version)

    system_prompt = generate_system_prompt(memo)

    # Build key variables
    key_vars = {
        "company_name": memo.company_name,
        "timezone": memo.business_hours.timezone if memo.business_hours else None,
        "business_hours_start": memo.business_hours.start if memo.business_hours else None,
        "business_hours_end": memo.business_hours.end if memo.business_hours else None,
        "business_days": memo.business_hours.days if memo.business_hours else [],
        "office_address": memo.office_address,
        "emergency_routing": [
            {
                "name": r.name,
                "phone": r.phone or "[PENDING]",
                "order": r.order,
            }
            for r in memo.emergency_routing_rules
        ],
        "transfer_timeout_seconds": (
            memo.call_transfer_rules.timeout_seconds
            if memo.call_transfer_rules
            else None
        ),
    }

    # Add pricing if available
    if memo.pricing_info:
        key_vars["pricing"] = memo.pricing_info.to_dict()

    # Add notification channels if available
    if memo.notification_channels and memo.notification_channels.email:
        key_vars["notification_email"] = memo.notification_channels.email

    # Build transfer protocol
    timeout = (
        f"{memo.call_transfer_rules.timeout_seconds}s"
        if memo.call_transfer_rules and memo.call_transfer_rules.timeout_seconds
        else "[NOT SET]"
    )
    retries = (
        memo.call_transfer_rules.retries
        if memo.call_transfer_rules
        else None
    )
    transfer_protocol = (
        f"Transfer to emergency routing list in order. "
        f"Timeout: {timeout}. "
        f"Retries: {retries if retries else '[NOT SET]'}."
    )

    fallback_protocol = (
        memo.call_transfer_rules.message_if_fails
        if memo.call_transfer_rules and memo.call_transfer_rules.message_if_fails
        else "Our team has been notified and will call you back shortly."
    )

    spec = AgentSpec(
        account_id=memo.account_id,
        agent_name=f"Clara — {memo.company_name}",
        version=memo.version,
        voice_style="professional-female-warm",
        system_prompt=system_prompt,
        key_variables=key_vars,
        tool_invocation_placeholders=[
            "transfer_call(phone_number)",
            "send_post_call_summary(caller_name, caller_phone, job_description)",
            "lookup_customer(phone_number)",
        ],
        call_transfer_protocol=transfer_protocol,
        fallback_protocol=fallback_protocol,
    )

    logger.info(
        "Agent spec generated: %s (prompt length: %d chars)",
        spec.agent_name, len(system_prompt),
    )

    return spec
